name: Deploy Backend to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy .NET Backend App to EC2
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip Backend Project (exclude .git)
        run: |
          zip -r EcommerenceBackend.zip . -x "*.git*"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

      - name: Upload to EC2
        run: |
          scp -o StrictHostKeyChecking=no EcommerenceBackend.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/EcommerenceBackend.zip

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<'EOF'
            echo "✅ Connected to EC2. Starting backend deployment..."

            # Clean and unzip
            rm -rf ~/EcommerenceBackend
            unzip -o ~/EcommerenceBackend.zip -d ~/EcommerenceBackend
            cd ~/EcommerenceBackend

            # Stop and remove old containers
            sudo docker compose down || true

            # Remove old image manually if exists
            if sudo docker images --format '{{.Repository}}' | grep -Eq '^ecommerencebackend-ecommercebackend-webapi$'; then
              sudo docker rmi ecommerencebackend-ecommercebackend-webapi || true
            fi

            # Build and start containers
            sudo docker compose up -d --build

            echo "✅ Backend deployed and running on port 5000."
          EOF